--------------------------------------------------------
-- File created - Friday-February-24-2017  
--------------------------------------------------------
SET DEFINE OFF;

INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (1, 'Lettuce', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (2, 'Pickles', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (192, 'Extra Pickles', 0, '2Xpic');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (3, 'Tomatoes', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (4, 'Mustard', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (5, 'Ketchup', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (6, 'Mayo', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (7, 'American cheese', 0, 'che'); 
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (8, 'Cheddar cheese', 0, 'che');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (9, 'Swiss cheese', 0, 'che');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (10, 'Gouda cheese', 0, 'che');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (11, 'Blue cheese Sauce', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (12, 'Onions', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (13, 'Honey Mustard', 0, 'dre');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (14, 'Ranch', 0, 'dre');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (15, 'Italian', 0, 'dre');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (16, 'Provalogne cheese', 0, 'che');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (17, 'Pepper Jack', 0, 'che');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (19, 'Havarti cheese', 0, 'che');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (20, 'Sun-Dried Tomato Mayo', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (21, 'Zesty-Chipotle Mayo', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (117, 'Zesty Ranch Mayo', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (22, 'Smoked Ham With Honey', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (23, 'Diced Chicken Breast', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (24, 'Minced Carrots', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (27, 'Zesty Sauce', 0, 'sau');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (35, 'Chipotle Sauce', 0, 'sau');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (38, '1 cheese Stick', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (40, 'Bacon', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (193, 'Bacon', 0, 'fla');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (41, 'Sausage', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (194, 'Sausage', 0, 'fla');
-- Bagel
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (182, 'Cream Cheese', 0, 'fla');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (42, 'Extra Cream Cheese', 0, '182Xcrc'); 
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (43, 'Sour Cream', 0, 'fla');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (44, 'Blueberry', 0, 'fla');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (46, 'Asiago cheese', 0, 'fla');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (47, 'Plain', 0, 'fla');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (48, 'Cinnamon Raisin', 0, 'fla');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (49, 'Everything', 0, 'fla');
-- Warm muffin
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (187, 'Blueberry', 0, 'fla');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (188, 'Chocolate', 0, 'fla');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (189, 'Orange Cranberry', 0, 'fla');
--
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (50, 'Black Olives', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (52, 'Anchovies', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (53, 'Banana Peppers', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (54, 'Add Mushrooms', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (55, 'Green Olives', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (56, 'Blue cheese Cup', 0, 'sau');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (57, 'Buffalo Sauce Cup', 0, 'sau');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (58, 'Garlic Sauce Cup', 0, 'sau');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (59, 'cheese Sauce Cup', 0, 'sau');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (60, 'Honey Mustard Cup', 0, 'sau');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (61, 'Barbeque Sauce Cup', 0, 'sau');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (62, 'Fresh-Sliced Onions', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (63, 'Green Peppers', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (64, 'Pepperoni', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (65, 'Roma Tomatoes', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (66, 'Black Olives', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (67, 'Jalapeño', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (68, 'Banana Peppers', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (69, 'Baby Portabella Mushrooms', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (72, 'Beef', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (74, 'Italian Sausage', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (75, 'Canadian Bacon', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (76, 'All-White Chicken', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (51, 'Thin Crust', 0, 'cru'); 
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (77, 'Pan Crust', 0, 'cru');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (191, 'Stuffed Crust', 1.00, 'cru');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (78, 'Extra Bacon', .75, '40Xbac');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (79, 'Extra Sausage', .75, '41Xssg');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (80, 'Hawaiian BBQ Chicken', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (81, 'Chicken', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (82, 'Italian Seasoning', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (83, 'Spicy Buffalo Sauce', 0, 'sau');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (84, 'Ranch Sauce', 0, 'sau');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (85, 'BBQ Sauce', 0, 'sau');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (86, 'Spinach', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (87, 'Pineapple', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (88, 'Ham', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (89, 'Spinach Alfredo Sauce', 0, 'sau');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (183, 'Original Pizza Sauce', 0, 'sau');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (90, 'Chicken', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (91, 'Hickory-Smoked Bacon', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (92, 'Tangy Bbq Sauce', 0, 'sau');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (100, 'Egg', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (101, 'Garden Herb Tortilla Wrap', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (102, 'Tomato Basil Tortilla Wrap', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (103, 'Add BBQ Sauce', 0, 'sau');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (104, 'Croutons', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (105, 'Add Burger Patty', 1.90, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (106, 'Salsa', 0, 'sau');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (107, 'Regular', 0, 'cof');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (108, 'Decaf', 0, 'cof');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (184, '12 oz', 0, 'size');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (185, '16 oz', 0, 'size');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (186, '20 oz', 0, 'size');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (109, 'Sautéed Mushrooms', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (110, 'Crispy Fried Onions', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (111, 'Smokey-Chipotle Mayo', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (112, 'Ceasar', 0, 'dre');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (113, 'Lite Ranch', 0, 'dre');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (118, 'Kosher Sauerkraut', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (119, 'Chipotle Mayo', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (120, 'Spicy Brown Mustard', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (121, 'Craisins', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (123, 'Celery', 0, NULL);
-- Ice cream
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (125, 'Chocolate', 0, 'fla');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (126, 'Cookie Dough', 0, 'fla');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (127, 'Mint Chocolate Chip', 0, 'fla');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (128, 'Strawberry', 0, 'fla');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (129, 'Vanilla', 0, 'fla');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (130, 'Strawberry Topping', 0, 'top');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (131, 'Chocolate Topping', 0, 'top');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (132, 'Caramel Topping', 0, 'fla');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (133, 'Hot Fudge', 0, 'fud');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (134, 'Peanut Butter Fudge', 0, 'fud');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (135, 'Double Fudge Brownie', 0, 'fud');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (136, 'Whip Cream', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (180, 'Old-Fashioned Chocolate Milkshake', 0, 'fla');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (181, 'Old-Fashioned Vanilla Milkshake', 0, 'fla');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (195, 'Chocolate Malt', 0, 'fla');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (196, 'Vanilla Malt', 0, 'fla');
-- 
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (140, 'Oven Roasted', 0, NULL);
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (137, 'Spicy Buffalo Dipping Sauce', 0, 'sau');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (138, 'Honey Chipotle Dipping Sauce', 0, 'sau');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (139, 'Barbeque Dipping Sauce', 0, 'sau');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (141, 'Special Garlic Dipping Sauce', 0, 'sau');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (142, 'Pizza Dipping Sauce', 0, 'sau');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (143, 'Ranch Dipping Sauce', 0, 'sau');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (144, 'Blue cheese Dipping Sauce', 0, 'sau');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (145, 'Cheese Sauce Dipping Sauce', 0, 'sau');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (146, 'Fountain Drink', 0, 'fla');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (147, 'Brewed Sweet Tea', 0, 'fla');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (190, 'Brewed Unsweet Tea', 0, 'fla');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (148, 'Apple', 0, 'fla');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (149, 'Orange', 0, 'fla');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (150, 'Dill Pickle Chips', 0, 'side');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (151, 'Jalapeno Chips', 0, 'side');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (152, 'Original Chips', 0, 'side');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (153, 'Salt & Vinegar Chips', 0, 'side');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (154, 'BBQ Chips', 0, 'side');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (155, 'Chef Salad', 0, 'side');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (156, 'Asiago Ceasar Salad', 0, 'side');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (197, 'French Fries', 0,'side');
-- for sandwiches sizes
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (157, 'Half', -1.81, 'size');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (158, 'Half', -2.4, 'size');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (159, 'Half', -2, 'size');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (160, 'Half', -2, 'size');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (161, 'Half', -1.8, 'size');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (162, 'Half', -1.6, 'size');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (163, 'Half', -1.7, 'size');
-- for paninis sizes
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (164, 'Half', -2, 'size');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (165, 'Half', -1.8, 'size');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (166, 'Half', -2, 'size');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (167, 'Half', -1.64, 'size');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (168, 'Half', -1.04, 'size');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (169, 'Half', -1.04, 'size');
-- for wraps sizes
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (170, 'Half', -2.4, 'size');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (171, 'Half', -1.9, 'size');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (172, 'Half', -2.4, 'size');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (173, 'Half', -2.1, 'size');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (174, 'Half', -2.8, 'size');
-- for pizza sizes
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (175, '8"', -5, 'size');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (176, '16"', 0, 'size');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (177, '8"', -6.5, 'size');
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (178, '16"', 0, 'size');
--
INSERT INTO detail (detail_id_pk, detail_descr, detail_cost, group_name) VALUES (179, 'Whole', 0, 'size');
-- 198