--------------------------------------------------------
--  File created - Friday-February-24-2017   
--------------------------------------------------------
SET DEFINE OFF;

-- Breakfast Sandwiches
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (129, 1, 'Toasted Bagel', 'Blueberry, Cinnamon, Plain, Asiago Cheese, or Everything', 1.69, 'Y', '/Breakfast/Breakfast_Bagel.jpg', 'Front Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (1, 1, 'Bagel', 'Bacon or Sausage', 2.99, 'Y', '/Breakfast/Breakfast_BECBagel.jpg', 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (2, 1, 'Flatbread', 'Bacon or Sausage', 2.99, 'Y', '/Breakfast/Breakfast_BECFlatbread.jpg', 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (3, 1, 'Toaster', 'Bacon or Sausage', 2.99, 'Y', '/Breakfast/Breakfast_SECToaster.jpg', 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (4, 1, 'English Muffin', 'Bacon or Sausage', 2.79, 'Y', '/Breakfast/Breakfast_BECEnglishMuffin.jpg', 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (5, 1, 'Croissant', 'Bacon or Sausage', 2.99, 'Y', '/Breakfast/Breakfast_SECCroissant.jpg', 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (6, 1, 'Quesadilla', 'Bacon or Sausage, egg, and cheese between two tortillas, served with sour cream and salsa.', 2.99, 'Y', NULL, 'Front Window');
-- Breakfast Sides
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (8, 2, 'French Toast Sticks', 'Bite-sized pieces of French toast served with maple syrup.', 1.99, 'Y', '/Breakfast/Breakfast_FrenchToastSticks.jpg', 'Front Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (9, 2, 'Hash Browns', 'Crispy potatoes browned to a golden perfection.', 1.59, 'Y', '/Breakfast/Breakfast_HashBrowns.jpg', 'Front Window');
-- Bakery
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (10, 3, 'Cinnamon Roll', NULL, 2.19, 'Y', '/Breakfast/Breakfast_CinnamonRoll.jpg', 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (11, 3, 'Warm Muffin', 'Blueberry, Chocolate, or Orange Cranberry', 1.69, 'Y', NULL, 'Back Window');
-- Beverages
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (12, 4, 'Coffee', 'Regular * Decaf', 1.19, 'Y', '/Breakfast/Breakfast_Coffee.jpg', 'Front Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (13, 4, 'Fountain Drink or Brewed Tea', NULL, 2.09, 'Y', '/Breakfast/Breakfast_FountainDrink.jpg', 'Front Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (15, 4, 'Apple or Orange Juice', NULL, 1.59, 'Y', '/Breakfast/Breakfast_AppleAndOrangeJuice.jpg', 'Front Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (17, 4, 'Bottled Water', NULL, 1.6, 'Y', '/Breakfast/Breakfast_BottledWater.jpg', 'Front Window');
-- Burgers
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (18, 5, 'Cheeseburger', '1/3 Pound of beef smothered in American cheese.', 6.29, 'Y', '/Lunch Dinner/Burger_Single.jpg', 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (19, 5, 'Double Cheeseburger', '2/3 Pound of beef smothered in American cheese.', 8.19, 'Y', '/Lunch Dinner/Burger_Double.jpg', 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (20, 5, 'Triple Cheeseburger', '1 Pound of beef smothered in American cheese.', 9.99, 'Y', '/Lunch Dinner/Burger_Triple.jpg', 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (21, 5, 'Bacon Burger', '1/3 Pound of beef and bacon smothered in American cheese.', 7.29, 'Y', '/Lunch Dinner/Burger_BaconSingle.jpg', 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (22, 5, 'Double Bacon Burger', '2/3 Pound of beef smothered in American cheese.', 9.19, 'Y', '/Lunch Dinner/Burger_BaconDouble.jpg', 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (23, 5, 'Mushroom Swiss Burger', '1/3 Pound of beef covered with sautéed mushrooms and real Swiss cheese.', 9.19, 'Y', '/Lunch Dinner/Buger_Mushroom.jpg', 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (24, 5, 'Sweet Heat BBQ Burger', '1/3 Pound of beef topped in Cheddar cheese, crispy fried onions, sweet heat BBQ sauce, and a smoky chipotle mayo.', 9.19, 'Y', '/Lunch Dinner/Burger_Sweetheart.jpg', 'Back Window');
-- Soups & Salads
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (34, 7, 'Broccoli Cheddar Soup', NULL, 1.89, 'Y', '/Lunch Dinner/Soup_CheddarBroccoli.jpg', 'Salads');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (35, 7, 'Old-Fashioned Chicken Noodle Soup', NULL, 1.89, 'Y', '/Lunch Dinner/Soup_ChickenNoodle.jpg', 'Salads');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (36, 7, 'Chicken and Wild Rice', NULL, 1.89, 'Y', '/Lunch Dinner/Soup_ChickenWildRice.jpg', 'Salads');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (40, 7, 'Salad', NULL, 7.39, 'Y', '/Lunch Dinner/Side_Salad.jpg', 'Salads');
-- Sandwiches
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (47, 8, 'Smoke House Turkey', 'Mesquite-somked turkey, Gouda cheese, and sun-dried tomato mayo on focaccia.', 6.4, 'Y', '/Lunch Dinner/Sandwich_SmokeHouseTurkey.jpg', 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (49, 8, 'Havarti Roast Beef', 'Top round roast beef, Havarti cheese, and zesty chipotle mayo on Italian ciabatta.', 7.09, 'Y', '/Lunch Dinner/Sandwich_RoastBeef.jpg', 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (51, 8, 'Mesquite Turkey Club', 'Mesquite turkey, hickory bacon, and smoked ham, with honey mustard and mayo with caraway rye.', 6.29, 'Y', '/Lunch Dinner/Sandwich_MisquiteTurkeyClub.jpg', 'Front Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (53, 8, 'Smoked Ham and Cheddar', 'Smoked ham and aged cheddar on marble rye with honey mustard and mayo.', 6.29, 'Y', '/Lunch Dinner/Sandwich_HamandCheddar.jpg', 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (55, 8, 'Chicken Bacon Ranch', 'Season grilled chicken breast, bacon, and zesty ranch mayo spread on wheatberry.', 5.79, 'Y', '/Lunch Dinner/Sandwich_ChickenBacon.jpg', 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (57, 8, 'Classic BLT', 'Hickory smoked bacon, lettuce, mayo, and thick tomato slices on wheatberry.', 5.49, 'Y', '/Lunch Dinner/Sandwich_BLT.jpg', 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (59, 8, 'Premium Chicken Salad', 'Prepared with diced chicken breast, minced carrots, and dill pickles on wheatberry.', 5.59, 'Y', '/Lunch Dinner/Sandwich_ChickenSalad.jpg', 'Back Window');
-- Hot Sandwiches
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (61, 8, 'Philly Cheesesteak', 'Tender ribeye steak cooked with bell peppers, onions, and smoked Gouda Cheese.', 6.09, 'Y', '/Lunch Dinner/Sandwich_PhillyCheesesteak.jpg', 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (62, 8, 'French Dip', 'Grilled roast beef au jus.', 6.09, 'Y', '/Lunch Dinner/Sandwich_FrenchDip.jpg', 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (63, 8, 'Cuban', 'Smoked Pork and Cuban ham with dill pickles, Swiss cheese, mayonnaise, and mustard.', 6.09, 'Y', '/Lunch Dinner/SandwichCuban.jpg', 'Back Window');
-- Paninis
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (64, 9, 'Roast Beef', 'Top round roast beef, Havarti cheese, and zesty chipotle mayo on toasted wheatberry.', 6.29, 'Y', '/Lunch Dinner/Panini_RoastBeef.jpg', 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (66, 9, 'Chicken Bacon Ranch', 'Grilled chicken, Havarti cheese, hickory bacon, and ranch mayo on toasted wheatberry.', 5.79, 'Y', '/Lunch Dinner/Panini_ChickenBaconRanch.jpg', 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (68, 9, 'Chipotle Turkey', 'Mesquite-somked turkey, Gouda cheese, hickory bacon, and chipotle mayo on toasted marble rye.', 6.29, 'Y', '/Lunch Dinner/Panini_ChipotleTurkey.jpg', 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (70, 9, 'Rueben', 'Corned beef topped with kosher  sauerkraut, Swiss cheese and zesty sauce on toasted rye.', 5.39, 'Y', '/Lunch Dinner/Panini_Ruben.jpg', 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (72, 9, 'Smoked Ham', 'Smoked ham, Havarti cheese, and spicy brown mustard on toasted rye.', 4.49, 'Y', '/Lunch Dinner/Panini_SmokedHam.jpg', 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (74, 9, 'Tuna Melt', 'Fresh tuna salad with melted Swiss on toasted marble rye.', 4.19, 'Y', '/Lunch Dinner/Panini_TunaMelt.jpg', 'Back Window');
-- Quesadillas
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (76, 10, 'Fiesta Chicken', 'Seasoned chicken with mozzarella cheddar, and Montery Jack cheese, and chipotle sauce.', 5.29, 'Y', '/Lunch Dinner/QuesadillaFiesta.jpg', 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (77, 10, 'Three Cheese', 'A blend of Cheddar, mozzarella, and Montery Jack Cheese', 4.99, 'Y', '/Lunch Dinner/QuesadillaThreeCheese.jpg', 'Back Window');
-- Wraps
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (78, 11, 'Mediterranean Turkey', 'Mesquite turkey, Gouda cheese, craisins, and sun-dried tomato mayo in a tomato basil tortilla.', 7.39, 'Y', '/Lunch Dinner/Wrap_Turkey.jpg', 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (80, 11, 'Wholesome Chicken', 'Upscale chicken salad prepared with grilled chicken breast, minced carrots, and a pickle in a multigrain tortilla.', 5.59, 'Y', NULL, 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (82, 11, 'Chicken Bacon Ranch', 'Season cuts of grilled chicken breast, somked bacon, and zesty ranch mayo in a garden vegetable tortilla.', 6.49, 'Y', '/Lunch Dinner/Wrap_ChickenBacon.jpg', 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (84, 11, 'Buffalo Chicken', 'Grilled chicken tossed in spicy buffalo sauce, with celery and bleu cheese sauce, in a garden vegetable tortilla.', 6.19, 'Y', '/Lunch Dinner/Wrap_BuffaloChicken.jpg', 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (86, 11, 'Premium Roast Beef', 'Top round roast beef, Havarti cheese, and chipotle mayo in a garden vegetable tortilla.', 6.59, 'Y', '/Lunch Dinner/Wrap_RoastBeef.jpg', 'Back Window');
-- Appetizers
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (25, 12, 'French Fries', NULL, 3.19, 'Y', '/Lunch Dinner/Side_Fries.jpg', 'Frier');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (26, 12, 'Chips and Fruit', NULL, 0, 'Y', '/Lunch Dinner/ChipsAndFruit.jpg', 'Front Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (89, 12, 'Mozerella Sticks', NULL, 3.19, 'Y', '/Appetizers/App_CheeseSticks.jpg', 'Frier');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (90, 12, 'Funnel Cake Fries', NULL, 3.19, 'Y', NULL, 'Frier');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (91, 12, 'Apple Pie Bites', NULL, 3.19, 'Y', '/Appetizers/App_AppleBites.jpg', 'Frier');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (92, 12, 'Macaroni and Cheese Bits', NULL, 3.19, 'Y', '/Appetizers/App_MacaroniBites.jpg', 'Front Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (93, 12, 'Onion Rings', NULL, 3.19, 'Y', '/Appetizers/App_OnionRings.jpg', 'Back Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (94, 12, 'Cheesy Jalapeño Bites', NULL, 3.19, 'Y', '/Appetizers/App_CheesyAppleBites.jpg', 'Frier');
-- Ice Cream
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (95, 13, 'Single Waffle', NULL, 2.49, 'N', '/Desserts/IceCream_SingleWaffle.jpg', 'Ice Cream');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (96, 13, 'Double Waffle', NULL, 3.39, 'N', '/Desserts/IceCream_DoubleWaffle.jpg', 'Ice Cream');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (97, 13, 'Single Dish', NULL, 2.29, 'N', '/Desserts/IceCream_SingleDish.jpg', 'Ice Cream');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (98, 13, 'Double Dish', NULL, 3.29, 'N', '/Desserts/IceCream_DoubleDish.jpg', 'Ice Cream');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (99, 13, 'Oreo', NULL, 3.49, 'N', '/Desserts/Sundaes_Oreo.jpg', 'Ice Cream');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (100, 13, 'Peanut Butter Cup', NULL, 3.49, 'N', '/Desserts/Sundaes_PeanutButterCup.jpg', 'Ice Cream');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (101, 13, 'Root Beer Float', NULL, 2.69, 'N', '/Desserts/Sundaes_RootBeerFloat.jpg', 'Ice Cream');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (102, 13, 'Old-Fashioned Milkshake/Malt', NULL, 3.25, 'N', '/Desserts/Sundaes_OldFashionedMilkshakeMelt.jpg', 'Ice Cream');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (103, 13, 'Brownie', NULL, 3.49, 'N', '/Desserts/Sundaes_Brownie.jpg', 'Ice Cream');
-- Pizza (classic, specialty, and create your own)
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (104, 14, 'Cheese', 'Signature Mozerella Cheese.', 4.99, 'Y', '/Papa Johns/PJ_CheesePizza.jpg', 'Pizza');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (105, 14, 'Pepperoni', 'Premium Pepperoni.', 4.99, 'Y', '/Papa Johns/PJ_PepperoniPizza.jpg', 'Pizza');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (106, 14, 'Sausage', 'Premium Sausage.', 4.99, 'Y', '/Papa Johns/PJ_SausagePizza.jpg', 'Pizza');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (107, 18, 'The Works', 'Pepperoni, Canadian bacon, spicy Italian sausage, black olives, baby portabella mushrooms, fresh-sliced onions, and green peppers.', 5.49, 'Y', '/Papa Johns/PJ_TheWorksPizza.jpg', 'Pizza');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (108, 18, 'The Meats', 'Pepperoni, sausage, beef, bacon, and Canadian bacon.', 5.49, 'Y', '/Papa Johns/PJ_TheMeatsPizza.jpg', 'Pizza');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (109, 18, 'Garden Fresh', 'Baby portabella mushrooms, black olives fresh sliced onions, green peppers and Roma tomatoes.', 5.49, 'Y', '/Papa Johns/', 'Pizza');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (110, 18, 'John''s Favorite', 'Peperoni, Sausage, a six-cheese blend, and Italian seasoning.', 5.49, 'Y', '/Papa Johns/PJ_JohnsFavoritePizza.jpg', 'Pizza');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (111, 18, 'Buffalo Chicken', 'Ranch sauce, all-white chicken, bacon, onions, mozzarella, a tangy, spicy buffalo sauce.', 5.49, 'Y', '/Papa Johns/PJ_BuffaloChickenPizza.jpg', 'Pizza');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (112, 18, 'Spicy Italian', 'Spinach, and a rich creamy garlic Parmasean alfredo sauce.', 5.49, 'Y', '/Papa Johns/PJ_SpicyItalianPizza.jpg', 'Pizza');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (113, 18, 'Spinach Alfredo', 'Spinach and a rich, creamy garlic Parmesan alfredo sauce.', 5.49, 'Y', '/Papa Johns/PJ_SpinachAlfredoPizza.jpg', 'Pizza');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (114, 18, 'BBQ Chicken and Bacon', 'BBQ sauce topped with all-white chicken, bacon, and onions.', 5.49, 'Y', '/Papa Johns/PJ_BBQChickenBacon.jpg', 'Pizza');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (115, 18, 'Hawaiian BBQ Chicken', 'BBQ sauce topped with chicken, bacon, onions, and pineapple.', 5.49, 'Y', '/Papa Johns/PJ_HawiianBBQPizza.jpg', 'Pizza');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (116, 18, 'Cheesy Chicken Cordon Bleu', 'Spinach alfredo sauce, all-white chicken, ham, and mozzarella, Asiago, provolone, and fontina cheese.', 5.49, 'Y', '/Papa Johns/PJ_ChickenCordonBleuPizza.jpg', 'Pizza');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (117, 18, 'Grilled Chicken Club', 'All-white chicken, hickery-smoked bacon, onions, and Roma tomatoes.', 5.49, 'Y', '/Papa Johns/PJ_GrilledChickenClubPizza.jpg', 'Pizza');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (118, 18, 'Tuscan Six Cheese', 'Parmesan, Romano, Asiago, fontina, provolone, and mozzarella.', 5.49, 'Y', '/Papa Johns/PJ_SixCheesePizza.jpg', 'Pizza');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (119, 18, 'Double Bacon Six Cheese', 'Bacon, Canadion bacon, mozzarella, Parmesan, Romano, Asiago, provolone, and fontina cheese.', 5.49, 'Y', '/Papa Johns/PJ_DoubleBaconSixCheesePizza.jpg', 'Pizza');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (120, 18, 'Spinach Alfredo with Chicken and Tomato', NULL, 5.49, 'Y', '/Papa Johns/PJ_SpinachAndAlfredoChickenAndTomatoPizza.jpg', 'Pizza');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (121, 17, 'Create Your Own', NULL, 5.49, 'Y', NULL, 'Pizza');
-- Sides (Papa John's)
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (122, 15, 'Garlic Parmesan Breadsticks (4)', 'Fresh original dough topped with our special garlic sauce & Parmesan Italian Seasoning.', 2.29, 'Y', '/Papa Johns/PJ_GarlicParmBreadsticks.jpg', 'Front Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (123, 15, 'Cheesesticks (12)', 'Fresh original dough topped with our special garlic sauce and real cheese.', 4.49, 'Y', '/Papa Johns/PJ_Cheesesticks.jpg', 'Front Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (125, 15, 'Papa''s Wings (8)', NULL, 5.49, 'Y', '/Papa Johns/PJ_OvenRoastedWings.jpg', 'Front Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (126, 15, 'Dipping Sauce', NULL, 0.69, 'Y', NULL, 'Front Window');
-- Desserts
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (127, 16, 'Mega Chocolate Chip Cookie', 'Filled with rich chocolate chips, baked fresh, then cut into 8 slices. Served warm and ready to eat.', 0, 'Y', NULL, 'Front Window');
INSERT INTO FOOD (food_id_pk, food_type_id_fk, food_name, food_descr, food_cost, is_deliverable, image_path, bb_group) VALUES (128, 16, 'Double Chocolate Chip Brownie', NULL, 0, 'Y', NULL, 'Front Window');
-- 130